// @generated by cmd/baker from configurations/9010.toml — DO NOT EDIT.
#![allow(clippy::all)]
use slisko_core::chassi::LineCardSpec;
use slisko_core::pixel::Position;
use slisko_core::traffic::ShaperConfig;

static LC0_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 985.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 78.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 99.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 117.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 138.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 156.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 177.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 195.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 216.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 233.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 254.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 290.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 311.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 329.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 350.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 368.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 389.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 407.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 428.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 446.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 467.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 531.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 552.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 570.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 591.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 609.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 630.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 648.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 669.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 687.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 708.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 744.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 765.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 783.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 804.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 822.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 843.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 861.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 882.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 900.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 921.0,
        size: 5.0,
    },
];
static LC0_LINK: &[usize] = &[
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
    27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
];
static LC0_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p10", 10),
    ("p11", 11),
    ("p12", 12),
    ("p13", 13),
    ("p14", 14),
    ("p15", 15),
    ("p16", 16),
    ("p17", 17),
    ("p18", 18),
    ("p19", 19),
    ("p2", 2),
    ("p20", 20),
    ("p21", 21),
    ("p22", 22),
    ("p23", 23),
    ("p24", 24),
    ("p25", 25),
    ("p26", 26),
    ("p27", 27),
    ("p28", 28),
    ("p29", 29),
    ("p3", 3),
    ("p30", 30),
    ("p31", 31),
    ("p32", 32),
    ("p33", 33),
    ("p34", 34),
    ("p35", 35),
    ("p36", 36),
    ("p37", 37),
    ("p38", 38),
    ("p39", 39),
    ("p4", 4),
    ("p40", 40),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("p9", 9),
    ("status", 0),
];
static LC1_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 73.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 180.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 280.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 380.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 530.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 635.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 740.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 845.0,
        size: 5.0,
    },
    Position {
        x: 73.0,
        y: 985.0,
        size: 5.0,
    },
];
static LC1_LINK: &[usize] = &[0, 1, 2, 3, 4, 5, 6, 7];
static LC1_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p2", 2),
    ("p3", 3),
    ("p4", 4),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("status", 8),
];
static LC2_POS: &[Position] = &[];
static LC2_LINK: &[usize] = &[];
static LC2_LABELED: &[(&str, usize)] = &[];
static LC3_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 73.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 180.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 280.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 380.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 530.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 635.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 740.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 845.0,
        size: 5.0,
    },
    Position {
        x: 73.0,
        y: 985.0,
        size: 5.0,
    },
];
static LC3_LINK: &[usize] = &[0, 1, 2, 3, 4, 5, 6, 7];
static LC3_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p2", 2),
    ("p3", 3),
    ("p4", 4),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("status", 8),
];
static LC4_POS: &[Position] = &[
    Position {
        x: 57.0,
        y: 187.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 198.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 57.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 57.0,
        y: 900.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 900.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 900.0,
        size: 4.0,
    },
];
static LC4_LINK: &[usize] = &[0];
static LC4_LABELED: &[(&str, usize)] = &[
    ("aco", 9),
    ("crit", 5),
    ("fail", 8),
    ("fc_fault", 3),
    ("gps", 4),
    ("maj", 6),
    ("min", 7),
    ("sso", 2),
    ("sync", 10),
];
static LC5_POS: &[Position] = &[
    Position {
        x: 57.0,
        y: 187.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 198.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 57.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 57.0,
        y: 900.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 880.0,
        size: 4.0,
    },
    Position {
        x: 43.0,
        y: 900.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 857.0,
        size: 4.0,
    },
    Position {
        x: 30.0,
        y: 900.0,
        size: 4.0,
    },
];
static LC5_LINK: &[usize] = &[0];
static LC5_LABELED: &[(&str, usize)] = &[
    ("aco", 7),
    ("crit", 6),
    ("fail", 9),
    ("fc_fault", 4),
    ("gps", 5),
    ("maj", 3),
    ("min", 8),
    ("sso", 2),
    ("sync", 10),
];
static LC6_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 73.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 180.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 280.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 380.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 530.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 635.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 740.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 845.0,
        size: 5.0,
    },
    Position {
        x: 73.0,
        y: 985.0,
        size: 5.0,
    },
];
static LC6_LINK: &[usize] = &[0, 1, 2, 3, 4, 5, 6, 7];
static LC6_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p2", 2),
    ("p3", 3),
    ("p4", 4),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("status", 8),
];
static LC7_POS: &[Position] = &[];
static LC7_LINK: &[usize] = &[];
static LC7_LABELED: &[(&str, usize)] = &[];
static LC8_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 73.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 180.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 280.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 380.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 530.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 635.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 740.0,
        size: 5.0,
    },
    Position {
        x: 76.0,
        y: 845.0,
        size: 5.0,
    },
    Position {
        x: 73.0,
        y: 985.0,
        size: 5.0,
    },
];
static LC8_LINK: &[usize] = &[0, 1, 2, 3, 4, 5, 6, 7];
static LC8_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p2", 2),
    ("p3", 3),
    ("p4", 4),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("status", 8),
];
static LC9_POS: &[Position] = &[
    Position {
        x: 75.0,
        y: 985.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 78.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 99.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 117.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 138.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 156.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 177.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 195.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 216.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 233.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 254.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 290.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 311.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 329.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 350.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 368.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 389.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 407.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 428.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 446.0,
        size: 5.0,
    },
    Position {
        x: 57.0,
        y: 467.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 531.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 552.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 570.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 591.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 609.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 630.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 648.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 669.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 687.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 708.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 744.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 765.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 783.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 804.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 822.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 843.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 861.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 882.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 900.0,
        size: 5.0,
    },
    Position {
        x: 56.0,
        y: 921.0,
        size: 5.0,
    },
];
static LC9_LINK: &[usize] = &[
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
    27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
];
static LC9_LABELED: &[(&str, usize)] = &[
    ("p1", 1),
    ("p10", 10),
    ("p11", 11),
    ("p12", 12),
    ("p13", 13),
    ("p14", 14),
    ("p15", 15),
    ("p16", 16),
    ("p17", 17),
    ("p18", 18),
    ("p19", 19),
    ("p2", 2),
    ("p20", 20),
    ("p21", 21),
    ("p22", 22),
    ("p23", 23),
    ("p24", 24),
    ("p25", 25),
    ("p26", 26),
    ("p27", 27),
    ("p28", 28),
    ("p29", 29),
    ("p3", 3),
    ("p30", 30),
    ("p31", 31),
    ("p32", 32),
    ("p33", 33),
    ("p34", 34),
    ("p35", 35),
    ("p36", 36),
    ("p37", 37),
    ("p38", 38),
    ("p39", 39),
    ("p4", 4),
    ("p40", 40),
    ("p5", 5),
    ("p6", 6),
    ("p7", 7),
    ("p8", 8),
    ("p9", 9),
    ("status", 0),
];
pub static CHASSIS: &[LineCardSpec] = &[
    LineCardSpec {
        name: "A9K-40GE-L",
        image: "a9k-40ge-l.png",
        active: true,
        positions: LC0_POS,
        link: LC0_LINK,
        status: Some(0),
        labeled: LC0_LABELED,
    },
    LineCardSpec {
        name: "A9K-8T-L",
        image: "a9k-8t-l.png",
        active: true,
        positions: LC1_POS,
        link: LC1_LINK,
        status: Some(8),
        labeled: LC1_LABELED,
    },
    LineCardSpec {
        name: "blank",
        image: "blank.png",
        active: false,
        positions: LC2_POS,
        link: LC2_LINK,
        status: None,
        labeled: LC2_LABELED,
    },
    LineCardSpec {
        name: "A9K-8T-L",
        image: "a9k-8t-l.png",
        active: true,
        positions: LC3_POS,
        link: LC3_LINK,
        status: Some(8),
        labeled: LC3_LABELED,
    },
    LineCardSpec {
        name: "A9K-RSP440-SE",
        image: "a9k-rsp440-se.png",
        active: true,
        positions: LC4_POS,
        link: LC4_LINK,
        status: None,
        labeled: LC4_LABELED,
    },
    LineCardSpec {
        name: "A9K-RSP440-SE-2",
        image: "a9k-rsp440-se.png",
        active: true,
        positions: LC5_POS,
        link: LC5_LINK,
        status: None,
        labeled: LC5_LABELED,
    },
    LineCardSpec {
        name: "A9K-8T-L",
        image: "a9k-8t-l.png",
        active: true,
        positions: LC6_POS,
        link: LC6_LINK,
        status: Some(8),
        labeled: LC6_LABELED,
    },
    LineCardSpec {
        name: "blank",
        image: "blank.png",
        active: false,
        positions: LC7_POS,
        link: LC7_LINK,
        status: None,
        labeled: LC7_LABELED,
    },
    LineCardSpec {
        name: "A9K-8T-L",
        image: "a9k-8t-l.png",
        active: true,
        positions: LC8_POS,
        link: LC8_LINK,
        status: Some(8),
        labeled: LC8_LABELED,
    },
    LineCardSpec {
        name: "A9K-40GE-L",
        image: "a9k-40ge-l.png",
        active: true,
        positions: LC9_POS,
        link: LC9_LINK,
        status: Some(0),
        labeled: LC9_LABELED,
    },
];

pub static ACTIVE_PATTERNS: &[&str] = &["greenstatus", "a9k-40ge-l", "a9k-8t-l", "a9k-rsp440-tr"];

pub struct LedOutput {
    pub gpio: u8,
    pub start: usize,
    pub end: usize,
}
pub static LED_TYPE: &str = "WS2815";
pub static LED_OUTPUTS: &[LedOutput] = &[
    LedOutput {
        gpio: 5,
        start: 0,
        end: 100,
    },
    LedOutput {
        gpio: 7,
        start: 100,
        end: 200,
    },
];

pub static SHAPER: ShaperConfig = ShaperConfig {
    enabled: true,
    peak_start: 17.0,
    peak_end: 22.0,
    low_start: 2.0,
    low_end: 7.0,
    peak_factor: 1.0,
    low_factor: 0.2,
};

pub struct Button {
    pub gpio: u8,
    pub scene: &'static [&'static str],
}
pub static BUTTONS: &[Button] = &[
    Button {
        gpio: 23,
        scene: &["greenstatus", "a9k-8t-l", "a9k-40ge-l", "a9k-rsp400-se"],
    },
    Button {
        gpio: 24,
        scene: &[],
    },
    Button {
        gpio: 25,
        scene: &[],
    },
    Button {
        gpio: 16,
        scene: &[],
    },
];
