// Command baker "bakes" a slisko TOML config into a Rust source module
// (generated.rs) consumed by the shared Rust configuration crate.
//
// It reuses the production config loader and chassis builder (pkg/configuration,
// pkg/chassi) so a baked board matches exactly what the RPI would render:
// resolved linecard tables (positions, link/status/labeled as card-local
// indices), the active pattern list, the [ledinfo] per-GPIO output map + LED
// type, the traffic-shaper params, and button->scene bindings.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"

	"github.com/anderstorpsfestivalen/slisko/pkg/chassi"
	"github.com/anderstorpsfestivalen/slisko/pkg/configuration"
	"github.com/anderstorpsfestivalen/slisko/pkg/pixel"
)

func main() {
	configPath := flag.String("config", "configurations/9010.toml", "input TOML config")
	outPath := flag.String("out", "firmware/slisko-config/src/generated.rs", "output Rust module")
	flag.Parse()

	conf, err := configuration.LoadFromFile(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "baker: %v\n", err)
		os.Exit(1)
	}

	cards := chassi.CardsFromDefinition(conf.Linecards)

	var b strings.Builder
	emit(&b, conf, cards, *configPath)

	if err := os.WriteFile(*outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "baker: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	rustfmt := exec.Command("rustfmt", "--edition", "2024", *outPath)
	rustfmt.Stdout = os.Stdout
	rustfmt.Stderr = os.Stderr
	if err := rustfmt.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "baker: format %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("baker: wrote %s (%d linecards, %d active patterns)\n", *outPath, len(cards), len(conf.Patterns))
}

func emit(b *strings.Builder, conf configuration.ChassiDefiniton, cards []chassi.LineCard, src string) {
	fmt.Fprintf(b, "// @generated by cmd/baker from %s — DO NOT EDIT.\n", src)
	b.WriteString("#![allow(clippy::all)]\n")
	b.WriteString("use slisko_core::chassi::LineCardSpec;\n")
	b.WriteString("use slisko_core::output::MappingSegment;\n")
	b.WriteString("use slisko_core::pixel::Position;\n")
	b.WriteString("use slisko_core::traffic::ShaperConfig;\n\n")
	b.WriteString("use crate::{Button, LedOutput};\n\n")

	// Per-card static tables.
	for i, card := range cards {
		emitCardTables(b, i, card)
	}

	// Chassis spec array.
	b.WriteString("pub static CHASSIS: &[LineCardSpec] = &[\n")
	for i, card := range cards {
		status := "None"
		if card.Status != nil {
			if idx := idxOf(card, card.Status); idx >= 0 {
				status = fmt.Sprintf("Some(%d)", idx)
			}
		}
		fmt.Fprintf(b, "    LineCardSpec { name: %q, image: %q, active: %t, positions: LC%d_POS, link: LC%d_LINK, status: %s, labeled: LC%d_LABELED },\n",
			card.Name, card.Image, card.Active, i, i, status, i)
	}
	b.WriteString("];\n\n")

	// Logical chassis -> physical strand mapping. The fixed LED_COUNT matches
	// the Go output buffer; a shorter mapping is implicitly padded with black.
	fmt.Fprintf(b, "pub const LED_COUNT: usize = %d;\n", conf.LEDAmount)
	b.WriteString("pub static OUTPUT_MAPPING: &[MappingSegment] = &[")
	for i, m := range conf.Mapping {
		if i > 0 {
			b.WriteString(", ")
		}
		if m.IsCard() {
			fmt.Fprintf(b, "MappingSegment::Card(%d)", *m.Card)
		} else {
			fmt.Fprintf(b, "MappingSegment::Gap(%d)", *m.Gen)
		}
	}
	b.WriteString("];\n\n")

	// Active patterns.
	b.WriteString("pub static ACTIVE_PATTERNS: &[&str] = &[")
	for i, p := range conf.Patterns {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", p)
	}
	b.WriteString("];\n\n")

	emitLedInfo(b, conf.LedInfo)
	emitShaper(b, conf.GetTrafficShaper())
	emitButtons(b, conf.Buttons)
}

func emitCardTables(b *strings.Builder, i int, card chassi.LineCard) {
	// Positions.
	fmt.Fprintf(b, "static LC%d_POS: &[Position] = &[", i)
	for j := range card.LEDs {
		pos := card.LEDs[j].GetPositon()
		if j > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "Position { x: %s, y: %s, size: %s }", rf(pos.X), rf(pos.Y), rf(pos.Size))
	}
	b.WriteString("];\n")

	// Link (card-local indices).
	fmt.Fprintf(b, "static LC%d_LINK: &[usize] = &[", i)
	for k, p := range card.Link {
		if k > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%d", idxOf(card, p))
	}
	b.WriteString("];\n")

	// Labeled (sorted by label for stable output).
	labels := make([]string, 0, len(card.Labeled))
	for l := range card.Labeled {
		labels = append(labels, l)
	}
	sort.Strings(labels)
	fmt.Fprintf(b, "static LC%d_LABELED: &[(&str, usize)] = &[", i)
	for k, l := range labels {
		if k > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "(%q, %d)", l, idxOf(card, card.Labeled[l]))
	}
	b.WriteString("];\n")
}

func emitLedInfo(b *strings.Builder, li *configuration.LedInfo) {
	if li == nil {
		b.WriteString("pub static LED_TYPE: &str = \"WS2812\";\n")
		b.WriteString("pub static LED_OUTPUTS: &[LedOutput] = &[];\n\n")
		return
	}
	fmt.Fprintf(b, "pub static LED_TYPE: &str = %q;\n", li.Type)
	b.WriteString("pub static LED_OUTPUTS: &[LedOutput] = &[")
	for k, out := range li.Mapping {
		start, end, _ := out.ParseRange()
		if k > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "LedOutput { gpio: %d, start: %d, end: %d }", out.Gpio, start, end)
	}
	b.WriteString("];\n\n")
}

func emitShaper(b *strings.Builder, s *configuration.TrafficShaper) {
	fmt.Fprintf(b, "pub static SHAPER: ShaperConfig = ShaperConfig { enabled: %t, peak_start: %s, peak_end: %s, low_start: %s, low_end: %s, peak_factor: %s, low_factor: %s };\n\n",
		s.Enabled, rf(float64(s.PeakStart)), rf(float64(s.PeakEnd)), rf(float64(s.LowStart)), rf(float64(s.LowEnd)), rf(s.PeakFactor), rf(s.LowFactor))
}

func emitButtons(b *strings.Builder, buttons []configuration.Button) {
	b.WriteString("pub static BUTTONS: &[Button] = &[\n")
	for _, btn := range buttons {
		gpio := gpioNum(btn.Pin)
		b.WriteString("    Button { gpio: ")
		fmt.Fprintf(b, "%d, scene: &[", gpio)
		for i, a := range btn.Action {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", a)
		}
		b.WriteString("] },\n")
	}
	b.WriteString("];\n")
}

// idxOf returns the card-local index of pixel p within card.LEDs, or -1.
func idxOf(card chassi.LineCard, p *pixel.Pixel) int {
	for i := range card.LEDs {
		if &card.LEDs[i] == p {
			return i
		}
	}
	return -1
}

// rf formats a float as a Rust f32 literal (always with a decimal point).
func rf(v float64) string {
	s := strconv.FormatFloat(v, 'f', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// gpioNum extracts the pin number from a "GPIO23"-style string.
func gpioNum(pin string) int {
	digits := strings.TrimFunc(pin, func(r rune) bool { return r < '0' || r > '9' })
	n, _ := strconv.Atoi(digits)
	return n
}
